[package]
name = "heart"
version = "0.1.0"
edition = "2021"
authors = ["Lukáš Hozda <luk.hozda@gmail.com>"]
description = "Hypermedia-based web development of the 1990 future!"
license = "Fair"

[dependencies]
ergokv = "0.1.7"
maud = "0.26.0"
tikv-client = "0.3.0"
warp = "0.3.7"
